import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/shared/NavBar/page";
import { AuthProvider } from "@/contexts/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CWR || Book Rental Service",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`px-4 md:px-10 lg:px-20 ${geistSans.variable} ${geistMono.variable} antialiased bg-cover bg-center`}
      >
        <AuthProvider>
          <NavBar />
          {children} {/* page.tsx of app folder */}
        </AuthProvider>
      </body>
    </html>
  );
}
